---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(cluster)
library(tidyverse)
library(foreach)
library(kmeans)
library(LICORS)
```
```{r cars}
singapore <- read.csv("C:/Users/yangxi/Desktop/R/exercise4/singapore.csv")
## summary no host_name,host_id,host_name, review_date
data=singapore[,c(-2,-3,-4,-13)]

## Convert to Category Data
data$Entire_Home <- 0 
data$Entire_Home[data$room_type == "Entire home/apt"] <- 1 

data$Private_room <- 0 
data$Private_room[data$room_type == "Private room"] <- 1 

data$Shared_room <- 0 
data$Shared_room[data$room_type == "Shared room"] <- 1 

data$Hotel_room <- 0 
data$Hotel_room[data$room_type == "Hotel room"] <- 1 

data$license[data$license == ""] <- "No_license"  
data$License<-1
data$License[data$license == "No_license"] <- 0

data$reviews_per_month[is.na(data$reviews_per_month)] <- 0

## first part of data
data_1=data[c('id','neighbourhood_group','neighbourhood','latitude','longitude','Entire_Home','Hotel_room',"Private_room','Shared_room','License')]
```


```{r cars}
##second Part of data

data_2=data[c("price", "minimum_nights", "number_of_reviews", "reviews_per_month", "availability_365")]

```


```{r}
X<-scale(data_2, center = TRUE, scale = TRUE)%>%as.data.frame()

ggcorrplot::ggcorrplot(cor(data_scale), hc.order = TRUE)
```


```{r}
k_grid = seq(2, 30, by=1)
SSE_grid = foreach(k = k_grid, .combine='c') %do% {
cluster_k = kmeans(X, k, nstart=30)
cluster_k$tot.withinss
}

elbow_sse=ggplot()+
  geom_point(aes(x=k_grid,y=SSE_grid))+
  ggtitle('SSE')+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
cluster1 = kmeanspp(X, k=5, nstart=25)

X['label']=factor(cluster1$cluster)
```


```{r}
PCA_data= prcomp(X, rank=5,scale=TRUE)
summary(PCA_data)

X['pca1']=PCA_data[['x']][,1]
X['pca2']=PCA_data[['x']][,2]
```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
g1=ggplot(data=X)+
  geom_point(aes(x=pca1,y=pca2,color=label))

g1
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
